### ISSUE TITLE
How to obtain props in the lifecycle of a page?

### ISSUE THREAD

**Issue by gXiaofei** [kotarella1110/vite-plugin-qiankun-lite#22]
How to obtain props in the lifecycle of a page?

**Comment by kotarella1110** [comment]
@gXiaofei 

You can obtain it from the arguments of the lifecycle hooks.

https://qiankun.umijs.org/guide/getting-started#1-exports-lifecycles-from-sub-app-entry

https://github.com/kotarella1110/vite-plugin-qiankun-lite/blob/500e74b0a2a4a2cb633d251d946c6883df1678a0/examples/react/src/main.tsx#L33-L36
