### ISSUE TITLE
适配 qiankun 时是否有额外需要注意的？

### ISSUE THREAD

**Issue by l246804** [kotarella1110/vite-plugin-qiankun-lite#25]
1. 对于 `__webpack_public_path__` 是否需要额外处理？
2. 是否需要使用 `@vitejs/plugin-legacy` 构建为非 `ESModule` 格式代码？

**Comment by deot** [comment]
> 1. 对于 `__webpack_public_path__` 是否需要额外处理？
> 2. 是否需要使用 `@vitejs/plugin-legacy` 构建为非 `ESModule` 格式代码？

- 如果部署的只有一个，直接修改`base`为cdn地址，作为生产环境。
- 另外可以试试`experimental.renderBuiltUrl`进行一个处理，但这个有个局限（css内的那些路径就无法动态了，这个只能项目内做特殊处理了）

`legacy`真的有必要么，我看`ESM`谷歌内核61以上(Released 2017-09-05), [浏览器支持表](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Guide/Modules)

**Comment by l246804** [comment]
> > 1. 对于 `__webpack_public_path__` 是否需要额外处理？
> > 2. 是否需要使用 `@vitejs/plugin-legacy` 构建为非 `ESModule` 格式代码？
> 
> * 如果部署的只有一个，直接修改`base`为cdn地址，作为生产环境。
> * 另外可以试试`experimental.renderBuiltUrl`进行一个处理，但这个有个局限（css内的那些路径就无法动态了，这个只能项目内做特殊处理了）
> 
> `legacy`真的有必要么，我看`ESM`谷歌内核61以上(Released 2017-09-05), [浏览器支持表](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Guide/Modules)

目前不仅仅是部署一个，而且公司内部已经有比较成熟的基座应用了，对接方式只能改造子应用，对于 `webpack` 直接修改 `__webpack_public_path__`，然而 `vite` 的 `experimental.renderBuiltUrl` 目前不是很满足，至于 `ESM` 考虑的是 JS 沙箱问题，或者插件已经处理好了？

**Comment by deot** [comment]
如果你部署多个，资源指向一个的话`base`也是没问题的。ESM沙箱内部也考虑的了，反正内部就replace了，比如
- `window -> __QIANKUN_WINDOW__["appName"].window`
- `document -> __QIANKUN_WINDOW__["appName"].document`

具体替换你可以看看这里。
https://github.com/kotarella1110/vite-plugin-qiankun-lite/blob/a18501ce79ead3a510ea0bfc3cce19f5e681ddcf/packages/vite-plugin-qiankun-lite/src/babel-plugin-transform-global-variables/index.ts#L12

如果遇到第三方库编译报错，这个我基本对项目内的alias对资源做了fix（比如强制指向min或umd文件），或升级依赖。至于为什么会出现我还在排查中....主要在下面的代码
https://github.com/kotarella1110/vite-plugin-qiankun-lite/blob/a18501ce79ead3a510ea0bfc3cce19f5e681ddcf/packages/vite-plugin-qiankun-lite/src/babel-plugin-transform-global-variables/index.ts#L32

我目前还没尝试`legacy`, 个人觉得他问题不大
